TrajectoryPlannerROS:
  max_vel_x: 0.6
  min_vel_x: 0.05
  max_rotational_vel: 1   
  min_in_place_rotational_vel: 0.01
  min_in_place_vel_theta: 0.01
  max_vel_theta: 0.8
  min_vel_theta: -0.8
  acc_lim_th: 8
  acc_lim_x: 5
  acc_lim_y: 5

  holonomic_robot: true
