obstacle_range: 2.5
raytrace_range: 8
footprint: [[-0.28,-0.24],[-0.28,0.24], [0.28, 0.24], [0.28,-0.24]]
#robot_radius: ir_of_robot
inflation_radius: 0.1
cost_scaling_factor: 10.0
observation_sources: scan
scan: {sensor_frame: base_link,  observation_persistence: 0.0, max_obstacle_height: 0.4, min_obstacle_height: 0.0, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

